### ISSUE TITLE
Module Requests

### ISSUE THREAD

**Issue by andrewtlove** [bigcompany/hook.io#109]
+ csv-write-stream
+ request

Thank you! :)

**Comment by Marak** [comment]
Installed.

FYI, modules should now auto-install if you attempt to require them in a service.

Manually additional of modules is being phased out.

**Comment by andrewtlove** [comment]
Awesome, thanks! :)

Cheers,

Andrew Love
p  (714) 496-7282
e  me@andrewtlove.com
