### ISSUE TITLE
Log streaming may include logs of previously viewed hook

### ISSUE THREAD

**Issue by l337r007** [bigcompany/hook.io#112]
#### Steps to reproduce: 
* `curl -v -N https://hook.io/Marak/echo/logs`
* Ctrl-C
* `curl -v -N https://hook.io/l337r007/test/logs`
* Browse https://hook.io/Marak/echo?foo=bar&hello=there&run=true

#### Expected:
nothing happens

#### Actual:
JSON log entries for `Marak/echo` appear

**Comment by Marak** [comment]
Good catch! Thank you.

Looks like the streaming `logSubscriber` isn't scoped to the specific hook path.

Should have this resolved today.

**Comment by Marak** [comment]
@l337r007 -

This *should* be resolved on production now.

Would you mind trying again?

**Comment by l337r007** [comment]
Just tried it again, doesn't seem to do that anymore. Thanks for the quick fix!

**Comment by Marak** [comment]
Thanks for the feedback!

Please let us know if you run into any other issues.

We are usually in #hook.io on irc.freenode.net
