### ISSUE TITLE
Can't login by email / password combination

### ISSUE THREAD

**Issue by Marak** [bigcompany/hook.io#119]
Appears to be a small bug on the front-end login that isn't allowing users to login with email / password combination.

Signup by email works.
Signup by account name works.
Login by account name and password works.
Github SSO works.

Login by email and password doesn't work.

Should have resolve in a day or two.

**Comment by Marak** [comment]
Should be resolved and deployed.

Will leave open for now.

**Comment by killswitch** [comment]
Tested it and it works. :+1:

**Comment by Marak** [comment]
Thank you for your feedback @killswitch !

Closing.
