### ISSUE TITLE
Taking forever to respond.

### ISSUE THREAD

**Issue by killswitch** [bigcompany/hook.io#121]
Getting this error:
> Request Aborted! Hook source code took more than 10 seconds to call hook.res.end()

> A delay of this long usually indicates there is an error in the source code for the Hook. 
Check source code to ensure hook.res.end() is being called. 

> If there are no errors and the Hook actually requires more than 10 seconds to execute, please contact hookmaster@hook.io and we can increase your timeout limits.

When calling a hook that makes use of `request` module.

**Comment by Marak** [comment]
Can you provide a link to the hook?

**Comment by killswitch** [comment]
http://slack-weather.hook.io/?text=dubuque,ia
or 
http://hook.io/killswitch/slack-weather?text=dubuque,ia

This hook was working no problem for a while, then a user of my slack said the command wasn't responding.

**Comment by Marak** [comment]
Based on http://hook.io/killswitch/slack-weather/source, I think it's most likely that 3rd party API taking too long to respond.

The API endpoint being: http://api.openweathermap.org/data/2.5/weather

If that is the case, you can try two things here:

1. Cache the hook by setting `module['exports'].cache = 60000` , where 60000 is ms.

2. Upgrade to the basic hosting plan and have your timeouts increased.

**Comment by killswitch** [comment]
I've done some tests locally with it and openweathermap.org responds very quickly every time.

**Comment by Marak** [comment]
Since the Hook is public, I can also see that it's currently in `Development` mode. You can improve performance by setting the mode to `Production`

**Comment by Marak** [comment]
@killswitch -

I can run http://hook.io/marak/examples-simplehttprequest/source a bunch here without seeing any timeouts. It never times out.

There isn't any good reason a request should take more than 10 seconds. If there is an issue with the stack here I'd like to identify it and fix it.

**Comment by Marak** [comment]
openweathermap.org seems to require payment for certain usage of their API. 

http://openweathermap.org/price

Is it possible we've hit some sort of API limit? Maybe it's trying to JSON.parse a really big string?

**Comment by killswitch** [comment]
Don't think so. Your run count shows 28 calls since creation.

**Comment by Marak** [comment]
What is suppose to happen if http://hook.io/killswitch/slack-weather is hit without `params.text` defined?

**Comment by Marak** [comment]
I'd also ask, can you get http://hook.io/marak/examples-simplehttprequest to timeout at all?

The tie-breaker would be if you created a new service that called somewhere besides openweather.

I believe you are getting the timeouts for your service. I can see them here.

**Comment by killswitch** [comment]
Without `params.text` It defaults in openweatherapi.

**Comment by Marak** [comment]
@killswitch -

Did you have any luck with this? The service seems to be performing OK right now?

I'm currently not seeing timeouts.

**Comment by killswitch** [comment]
Yup seems to be working with no change on my end. @Marak

**Comment by Marak** [comment]
@killswitch -

Okay. Please let me know if you see this behavior again.

Due to the simple nature of your service, it's important we understand why this happened.

I'm still assuming that the issue was caused by lag on the side of openweather, but without any proof we just don't know. I haven't seen this behavior with any other hooks.

If there are any issues with our platform, we will find them and fix them.

Thank you for your feedback.

**Comment by killswitch** [comment]
No problem. I'll be adding a few more slack related hooks, so I'll keep an eye on stuff and try to get as much info about them as possible.
