### ISSUE TITLE
Can't send tweets.

### ISSUE THREAD

**Issue by meanJim** [bigcompany/hook.io#122]
I have a gist that I can run locally without any issues. The only difference between my hook.io usage and my node CLI usage is this line

```
#! /usr/bin/env node
```

Here is the gist:
https://gist.github.com/meanJim/75f5fb931bc6665c9dfe

When I try on hook.io I run into this bug: (and you can try too! with: `http://hook.io/jim/tweet`, be sure to use query params for all the arguments)
```
body: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}' },
```

I would appreciate the help, I understand the bug is trivial in nature and probably not specific enough for the hook.io issue tracker, but maybe someone knows some obvious differences / quirks that I need to account for. Thanks!!

**Comment by Marak** [comment]
@meanJim -

Can you try regenerating your twitter access tokens?

**Comment by Marak** [comment]
That 32 error message is coming from Twitter FYI.

**Comment by meanJim** [comment]
Yeah I've done it twice, It works locally I'm tweeting using those current tokens

**Comment by Marak** [comment]
Don't think you can re-use the tokens in two places.

**Comment by meanJim** [comment]
I see, so if I regenerate the tokens, hook.io can be the only source that uses them?

**Comment by Marak** [comment]
I'll have to re-read Twitter's oauth workflow docs again.

Twitter services are pretty key, we will get to the bottom of this.

Will most likely have a Twitter example to fork from.

**Comment by meanJim** [comment]
My coworker was able to take my script and run it on his computer and tweet to the account

**Comment by Marak** [comment]
@meanJim - What version of `twitter` are you using?

**Comment by meanJim** [comment]
Repo: https://github.com/desmondmorris/node-twitter
Version: `1.2.5`

**Comment by Marak** [comment]
I'll continue to investigate. I'm sorry it's not working as expected.

We'll have something sorted out in the next day or two.

Thank you for your feedback.

**Comment by meanJim** [comment]
No problem @Marak ! Thanks a ton for looking into this.

**Comment by meanJim** [comment]
@Marak discovered that its a regression from `toLowerCase()` on all urls. I'm closing this issue since that problem isn't stopping me from tweeting anymore.

I love what you guys have going on here! Thanks for a day of fun
