### ISSUE TITLE
invoices for paid plans?

### ISSUE THREAD

**Issue by logemann** [bigcompany/hook.io#130]
Do you offer "invoices" for your paid plans? We definitely need them because its for our company. If yes, do you send them monthly via email or can we download them?

**Comment by Marak** [comment]
@logemann -

As part of the stripe integration, you should receive billing statements as email. We'll most likely customize these emails.

What I can additionally do is provide an area on the `/account` page where users can browse / download their past invoices.

**Comment by logemann** [comment]
This would be perfect, so i assume there is a place in the account page, where you can enter your "company information", which is then printed on the invoice in the "receiver" part.

**Comment by Marak** [comment]
I'll make a few updates to the UI to include a section for basic invoice management.

Should have something ready in the next day or two.

Thank you for the feedback.

**Comment by Marak** [comment]
Haven't forgotten about this issue @logemann 

A bit backed up with platform features.

We have all billing data stored in Wtripe and there are a lot of Stripe integrations for generating nice invoices automatically. We'll be able to flip the switch on this with relative ease.

Will update issue when we have progress.

**Comment by logemann** [comment]
yeah. Keep me updated. Will take actions when its ready.
