### ISSUE TITLE
Language request: add babel

### ISSUE THREAD

**Issue by ljharb** [bigcompany/hook.io#140]
Many people who were using Coffeescript for some reason have migrated to babel so they can write standard ES6 JavaScript even if `node` doesn't support all of it yet. It'd be great if you could support babel.

**Comment by Marak** [comment]
Seems like it should be easy to add.

I'll see if I can add support in the next week.

Thanks for the suggestion @ljharb!

**Comment by himynameisdave** [comment]
@Marak hey! just curious what the status of this is? Would love to use some promise-based ES6 stuff.

**Comment by ljharb** [comment]
@himynameisdave fwiw, Promises are native in node 0.12 and later, and babel doesn't transpile API, just syntax, so you shouldn't need this feature to work with promises (assuming the node version is 0.12 or higher)

**Comment by Marak** [comment]
I've got `babel-core` working locally now and have added a new hook language type `es7`.

This should transpile all es6+ code into something `run-hook` can work with.

Should have this deployed and ready for testing soon.

**Comment by Marak** [comment]
This is now deployed and resolved in production.

https://hook.io/marak/examples-es7-hello-world/source

I'm sure there will be some additional edge cases with the es6+ support, please let me know if you run into any issues.

**Comment by himynameisdave** [comment]
Very cool, thanks @Marak :tada:
