### ISSUE TITLE
Regression of datastore

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#143]
```Console
/node_modules/hook.io-datastore/index.js:152
  client.get('/ds/' + self.root + "/" + key, function(err, reply){
        ^
Cannot read property 'get' of undefined
```

**Comment by Marak** [comment]
@pyhedgehog -

Thanks good catch.

Should be sorted out now.

We'll be rolling out our integration tests soon so hopefully we'll see less regressions.

**Comment by hobofan** [comment]
Has there also be a problem with old data coming alive?

We use hook.io for storing which docker image should be deployed in our CI pipline and 1-2 hours ago a old images deployed and the corresponding data in hook.io is very old. As far as we can see nothing was executed in our CI pipline.

**Comment by Marak** [comment]
@hobofan -

We had a small regression with the datastore this morning causing the datastore to not be accessible for the past 24 hours.

It should be restored now. Could you try again?

You can join #hook.io on irc.freenode.net for additional assistance.

**Comment by Marak** [comment]
@hobofan -

Any luck? 

If you are using the hook.io APIs for anything business related or important we can help provide better support if you can provide us with a bit of information about your service / how you are using our APIs.

In other words, we can give you service priority support so issues like this can be proactively resolved moving forward.

**Comment by hobofan** [comment]
Luckily we had all relevant data also stored elsewhere and were able to reenter the data into the hooks so it doesn't effect us anymore.

**Comment by Marak** [comment]
Resolved on production. Commit coming shorty.

Closing for now.
