### ISSUE TITLE
did we reach our monthly limit?

### ISSUE THREAD

**Issue by logemann** [bigcompany/hook.io#148]
Hi,

how can i see if i reached the monthly limit? I am still on the free plan and wondering why things just dont work anymore.

**Comment by Marak** [comment]
What's the issue? Which hook?

We rolled out a bunch of updates last night. Suffering a few regressions today.

**Comment by Marak** [comment]
Live support is also available in #hook.io on irc.freenode.net

We've couple a couple people in there on a few timezones.

**Comment by logemann** [comment]
Sorry. my problem. Hook is fine. Slack stopped receiving my GET request. Please close.
Thanks for the irc hint.

**Comment by Marak** [comment]
@logemann 

I appreciate the feedback.

Is there anything we could do in the Hook API to make errors like this more apparent in the future?

FYI, we'll be rolling out integration tests very soon https://github.com/bigcompany/hook.io-test

**Comment by Marak** [comment]
Also...technically we haven't implemented a max for anyone yet see: https://github.com/bigcompany/hook.io/issues/124

So you shouldn't worry about hitting limits anytime soon.
