### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by cathalgarvey** [bigcompany/hook.io#158]
I note that Hook supports Python 2, which is a nice start, but is already outdated. Are ye planning to support a more modern version of Python, such as 3.4 or even 3.5?

Thanks!

**Comment by Marak** [comment]
I see the server is on:

`Python 2.7.6`

There's no reason why can't move to 3.x. I just have the check compatibility with Node.js and npm because I know it uses Python for some things.

I'll see what we can do. Thanks!

**Comment by waylonflinn** [comment]
:+1:

**Comment by Marak** [comment]
The people have spoken!

I've updated the priority of this issue and have placed the feature On Deck. Will have an update shortly.

If anyone is interested in tracking hook.io feature development we have a public Trello board available here: https://trello.com/b/9i9QSbof/hook-io-features

**Comment by Marak** [comment]
I did some research and have found that `node-gyp` and `gyp` will never support python3.

That's okay, as we can easily have both versions exist on production.

Will install `python3` on production in the next day.

Sorry for the delay. Was traveling during the week.

**Comment by waylonflinn** [comment]
Perfect timing! I was just thinking about how to spin up my own on AWS.

**Comment by cathalgarvey** [comment]
Fantastic news, thanks! You made my breakfast. :)

On 10 October 2015 23:28:35 IST, Waylon Flinn <notifications@github.com> wrote:
>Perfect timing! I was just thinking about how to spin up my own on AWS.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bigcompany/hook.io/issues/158#issuecomment-147130642

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Marak** [comment]
Got everything working locally in testing.

The only concern I have now is that a few users have already created hooks using python2.

Do you think we can drop support for python 2 entirely? Or should we keep both versions available?

**Comment by Marak** [comment]
Since it's not going to be that difficult to support both, I'm going to keep support for both versions.

Will need to update the examples and should have this deployed in the next few hours.

**Comment by waylonflinn** [comment]
Yay!



Good call on Python 2. The tide is finally turning, but lots haven't moved yet.





—

**Comment by Marak** [comment]
We should now have support for both `python` and `python3` online.

http://hook.io/marak/examples-python3-hello-world
http://hook.io/marak/examples-python3-hello-world/source

Please let me know if you run into any issues. Thanks!

Sorry again this took so long to turn around. Lost about a week to travel. I will now be more available.

**Comment by louis77** [comment]
Hi guys

I've recently joined the Python developers community and know that there is still some discussion around version 2 and version 3. Personally, I don't see the point in supporting an old version of Python for hook.io, since hook.io is not about deploying existing apps. Most likely one will write new functions to be deployed here. 

Python 3 supports a lot of new features and cleans up the language a lot. Also performance is a big plus in Python 3 from my experience. It was released 2008, so it's not that new after all. If there is a decision to support Python 2 too, why not supporting Ruby 1, Node 0.x, and all the other old versions of all the other languages too?

**Comment by cathalgarvey** [comment]
Having started allowing customers to use Py2 the Hook people have a responsibility not to simply pull the rug right away, though with a sunset on Py2 support in the nnear future it'll eventually happen.

A mid-road option is to simply disallow *new* projects using outdated and soon discontinued runtimes, which limits technical debt to existing code only. However, the burden of maintaining that technical debt lies with the Hook team so it's their call.

I'm just grateful for the upgrade! :)

On 12 October 2015 09:45:05 IST, Louis Brauer <notifications@github.com> wrote:
>Hi guys
>
>I've recently joined the Python developers community and know that
>there is still some discussion around version 2 and version 3.
>Personally, I don't see the point in supporting an old version of
>Python for hook.io, since hook.io is not about deploying existing apps.
>Most likely one will write new functions to be deployed here. 
>
>Python 3 supports a lot of new features and cleans up the language a
>lot. Also performance is a big plus in Python 3 from my experience. It
>was released 2008, so it's not that new after all. If there is a
>decision to support Python 2 too, why not supporting Ruby 1, Node 0.x,
>and all the other old versions of all the other languages too?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bigcompany/hook.io/issues/158#issuecomment-147330505

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Marak** [comment]
We already made the decision to support both versions.

**Comment by pyhedgehog** [comment]
@cathalgarvey, @waylonflinn and @louis77, please join [discussion](https://github.com/bigcompany/hook.io/issues/236#issuecomment-271610555) important for python support.
