### ISSUE TITLE
Access resource information via hook.resource

### ISSUE THREAD

**Issue by joshgillies** [bigcompany/hook.io#161]
As an example via https://hook.io/Marak/echo/resource you get information relating to a hook. It could be useful to be able to query this information via `hook.resource` from inside a hook context.

**Comment by Marak** [comment]
This should be relatively easy to add.

I'll see if I can sneak it in the next deployment.

Thanks!

**Comment by Marak** [comment]
@joshgillies - 

I've now resolved this issue locally and will hopefully have it deployed soon.

Thank you for your feedback.

**Comment by Marak** [comment]
Resolved and deployed.
