### ISSUE TITLE
Meta properties are not safe

### ISSUE THREAD

**Issue by dolmen** [bigcompany/hook.io#166]
hook.io get some default properties: `owner`, `hook`, `gist`.
But these properties can not be trusted as a caller can override them from a query.

Example: https://hook.io/Marak/echo
```json
{
  "owner": "marak",
  "hook": "echo",
  "gist": "https://gist.github.com/Marak/357645b8a17daeb17458",
  "param1": "foo",
  "param2": "bar"
}
```
I can override all properties with this query: https://hook.io/Marak/echo?owner=a&hook=b&gist=c
```json
{
  "owner": "a",
  "hook": "b",
  "gist": "c",
  "param1": "foo",
  "param2": "bar"
}
```
As the values can not be trusted, it is dangerous to use them. If it is dangerous to use them, they become useless.
So they should not exist in the same scope as request content and instead be provided in a different object that can not be overriden.

**Comment by Marak** [comment]
The thing is...does it actually do anything dangerous?

Can you actually get this to do anything bad?

On the server, these variables exist in separate scope, and all role access checks should be performed against the owner and hook properties that come from the route itself ( not the query string or form post ).  We then merge everything together into one scope in the hook for convenience to the user.

If you can show me an actual security issue, I'd be glad to address it. From what you have posted so far, it seems it might just be

**Comment by Marak** [comment]
I'm curious, are you writing a hook which needs reliable access to these properties? If so, what is it doing?

If so, we actually do have that scope preserved. I'm not sure if we are sending it to the hook parameter, but we can.

**Comment by Marak** [comment]
@dolmen -

Any updates on this?

**Comment by pyhedgehog** [comment]
Just an example: https://hook.io/pyhedgehog/static/source

**Comment by dolmen** [comment]
@pyhedgehog What do you want to demonstrate?

**Comment by pyhedgehog** [comment]
@dolmen Sample code where value of `hook.req.params.gist` is important and security-sensible.

**Comment by monkbroc** [comment]
Implementing #161 would make this issue go away: document getting meta properties from `hook.resource` instead of `hook.params`.

Deprecate `hook.params.owner/hook/gist` (`console.log` when those properties are accessed) and eventually remove them.

**Comment by Marak** [comment]
I've resolved this locally by providing an additional `hook.resource` scope inside the hook service.

Like @monkbroc pointed out, you could just switch to checking `hook.resource.name` and it would be secure.

Will close the issue once this is deployed.

**Comment by Marak** [comment]
@dolmen -

This should now be resolved.

You may use the safe properties of `hook.resource` inside your service.

Thanks for your feedback!
