### ISSUE TITLE
hook.req.method is always "POST"

### ISSUE THREAD

**Issue by berak** [bigcompany/hook.io#168]
https://hook.io/berak/test_get

<pre>

module['exports'] = function datastoreExample (hook) {
  hook.res.end(hook.req.method);
};

</pre>

**Comment by Marak** [comment]
Yeah, that is a mistake @ https://github.com/bigcompany/run-remote-service/blob/master/index.js#L22

From what I can remember, there was a reason I switched all reverse proxied requests to use post internally.

I'll investigate a little and make sure we get the HTTP method preserved inside the context of the hook service.

**Comment by reimertz** [comment]
@Marak this still seems to be an issue.

**Comment by zanona** [comment]
Is there any workaround currently so we can only accept POST requests?

**Comment by Marak** [comment]
Should be resolve in production ( for good ).
