### ISSUE TITLE
Should logs be public

### ISSUE THREAD

**Issue by monkbroc** [bigcompany/hook.io#169]
Hook.io is a very nice service! The key is its simplicity. Nicely done!

I was surprised to find that the logs are publicly accessible. As the default example code dumps `hook.env` to the logs and the environment is meant for private secrets, that doesn't seem like a good idea.

An immediate change to improve this would be to make sure http://hook.io/logs warns that logs are publicly accessible.

Is there a way to purge the logs of private information? Maybe a "clear logs" button on the admin page? (I suppose I can write blank lines until the old lines go away, but maybe there's something else)

I don't mind that the hook code is public, but I feel that the logs should stay private, like the environment.

What do you think?

**Comment by monkbroc** [comment]
For example, by looking at https://hook.io/marak/static/logs I bet that your environment contains `{"env1":"val1","hello2":"there"}`

**Comment by Marak** [comment]
Thank you!

@monkbroc - Paid accounts will have the ability to set hooks to private. This would also makes logs private.

http://hook.io/pricing

**Comment by Marak** [comment]
On free accounts, all services will be public by default.

I think that's pretty fair. :-)

**Comment by monkbroc** [comment]
That's a fair decision :)

Just think what you can do to prevent users inadvertently leaking private information: change the default example not to log `hook.env`, warn that `console.log` output is public by default, add a line on the https://hook.io/user/hook/logs page "These logs are publicly visible", maybe add a "clear logs" button in case secret info makes it in the logs.

**Comment by Marak** [comment]
I think adding a "clear logs" button would be a great idea!

I will 100% add that feature.

In the mean-time, if you have accidentally leaked anything, you can just spam empty `console.log` statements as we only store the last `50`.

We need a general overall of privacy / security / encryption documentation on the site. It's important the users fully understand how their data and source code will be handled on our systems.

Thank you for the feedback, it's much appreciated.

**Comment by monkbroc** [comment]
Sounds good. You can close this issue unless you want to come back later and check my other docs/examples suggestions.

**Comment by Marak** [comment]
@monkbroc -

There is now an option for logs to be cleared.

Role 'hook::logs::read` is now restricted to anonymous access for private hooks.

The only way to view logs for a service ( which has been set to private ), is to login through the web admin, or provide a valid `hook_private_key` parameter.

The best way to see how this works is reviewing these tests:

https://github.com/bigcompany/hook.io-test/blob/master/tests/client/hook-logs-private-test.js 

Let me know how it works for you!

Thanks again for the feedback.
