### ISSUE TITLE
Workflow redirect improvement suggestions

### ISSUE THREAD

**Issue by monkbroc** [bigcompany/hook.io#173]
I ran into a few usability issues in the workflow.

When I create a new hook and press new, it immediately runs the webhook. This is potentially problematic if it's a webhook that must only run under certain conditions. It also is kind of a UI dead end: the hook execution page has no navigation links by default, and if I hit back, I go to the new form again. It's hard to find out how to edit the hook.
* Suggestion: Redirect to hook admin page after creation.

Saving the hook renders the admin interface in the POST request so I can't reload the page without the browser complaining.
* Suggestion: Redirect to hook admin page after save instead of rendering on the same request.

The Service URL section is full of links, but they are not clickable.
* Suggestion: Put the links in a tags

I'm going to bed now. I promise I won't open any more issues tonight :)

**Comment by Marak** [comment]
I think all of these are good and reasonable requests.

Thank you so much for your feedback, even bit really helps make the project better.

I'll make these changes in the web UI soon.

**Comment by Marak** [comment]
This is now resolved locally.

Will most likely deploy at the end of the day here along with some other updates we completed over the weekend.

**Comment by monkbroc** [comment]
:100: thanks!

**Comment by Marak** [comment]
Deployed. Closing issue.

@monkbroc - Please let me know if we missed anything. 

Thanks for your feedback!
