### ISSUE TITLE
Support ES7 async functions

### ISSUE THREAD

**Issue by mnmtanish** [bigcompany/hook.io#175]
ES7 async functions can get rid of most javascript callback functions. Makes it much easier to write code faster.

**Comment by Marak** [comment]
I think this could probably easily be added with only a few lines of code here:

https://github.com/bigcompany/hook.io/blob/master/bin/run-hook#L57

Then we make a new example like here:

https://github.com/bigcompany/hooks/blob/master/examples-coffee-script-hello-world/index.coffee

**Comment by Marak** [comment]
I've got `babel-core` working locally now and have added a new hook language type `es7`.

This should transpile all es6+ code into something `run-hook` can work with.

Should have this deployed and ready for testing soon.

**Comment by Marak** [comment]
@mnmtanish -

We should now have basic es7 support. This is my first time using es7, so please let me know if we are missing anything.

https://hook.io/marak/examples-es7-hello-world/source

**Comment by mnmtanish** [comment]
@Marak Thank you. I'll check it out.
