### ISSUE TITLE
Custom Timeouts aren't retained/displayed after form submit

### ISSUE THREAD

**Issue by andrewtlove** [bigcompany/hook.io#176]
When setting a custom timeout through the admin view, a value entered before hitting submit is not reflected on page refresh.

**Comment by Marak** [comment]
Probably bad logic with the billing check.

I'll try to take a look tonight. Didn't have much time to test.

The commit is here: https://github.com/bigcompany/hook.io/commit/26a00f4b2fb0f8746322a8847677cd23e264caf7

**Comment by Marak** [comment]
Should be resolved now. Was a minor typo.
