### ISSUE TITLE
IRC to Slack

### ISSUE THREAD

**Issue by gayanhewa** [bigcompany/hook.io#177]
Why not move to Slack instead of irc ? Quite easier to communicate.

**Comment by monkbroc** [comment]
This being an open-source project of GitHub, gitter is actually easier than Slack.

**Comment by linkaross** [comment]
As someone who just witnessed such a switch, i strongly advise not to do so.

There's so much more distraction, and the clients are not exactly "lightweight"

**Comment by pyhedgehog** [comment]
We can get most important feature of gitter (log) by registering some logging bot on IRC channel.
I've seen docker using https://botbot.me/ for example. Subscription request should be send by channel op.

**Comment by sbruchmann** [comment]
> Why not move to Slack instead of irc ?

[Please don't use Slack for FOSS projects](https://drewdevault.com/2015/11/01/Please-stop-using-slack.html).

**Comment by Marak** [comment]
I haven't been that diligent in staying in the IRC room or communicating with users outside of Github Issues or direct Support Emails.

I don't plan on logging into Slack or Gitter everyday, it's too much of a distraction for me. I barely visit IRC as it is.

FYI, we have a big update coming soon.

Cheers.
