### ISSUE TITLE
setTimeout not defined inside hook

### ISSUE THREAD

**Issue by monkbroc** [bigcompany/hook.io#178]
I cannot use `setTimeout` inside a Javascript hook to handle the timeout of an external operation. Is there a way to have access to `setTimeout` inside hook code?

This simple hook
```
module['exports'] = function echoHttp (hook) {
  hook.res.write("Begin\n");
  setTimeout(function () {
    hook.res.end("End\n");
  }, 1000);
};
```

return

```
Begin
evalmachine.<anonymous>:3
  setTimeout(function () {
  ^
setTimeout is not defined
```

**Comment by kulakowka** [comment]
I copied your example and launched its in hook.io mainpage. it's works.

But when i try run it on https://hook.io/kulakowka/settimeout i recieve error too:

```
Begin
evalmachine.<anonymous>:3
  setTimeout(function () {
  ^
setTimeout is not defined
```

@Marak you could see what is the reason?

**Comment by Marak** [comment]
Yes. This should be resolved locally with https://github.com/bigcompany/hook.io/commit/36b9d63fa8521e67f77e1688065afa85020fcaa7

I'm way behind with deploying the latest changes.

Will try to have it resolved in production soon.

**Comment by Marak** [comment]
Okay.

I was able to get the previous commits deployed and `setTimeout` should be back again.

Example:
https://hook.io/marak/set-timeout/source

Let me know if that works out for you.

**Comment by monkbroc** [comment]
Thanks @marak
