### ISSUE TITLE
hook.io website down?

### ISSUE THREAD

**Issue by VerstandInvictus** [bigcompany/hook.io#182]
The website has been timing out on everything I do for the last ~6 hours. Multiple connections and locations. What's up?

**Comment by Marak** [comment]
Ugh. It's a billing problem with DigitalOcean. I've been trying to get in touch with them all week.

Getting on the phone now.

**Comment by Marak** [comment]
@VerstandInvictus -

Services should be back online now. 

Working with DigitalOcean now to see if we can get a proper sponsorship.

**Comment by Marak** [comment]
Getting timeouts now as well.

Looking into it.

**Comment by Marak** [comment]
Okay. After server restarts we have to run this command in order to get the chroot jail working again.

``` bash
mount -o bind /proc /var/chroot/proc
mount -o bind /dev /var/chroot/dev
mount -o bind /dev/pts /var/chroot/dev/pts
mount -o bind /sys /var/chroot/sys
```

Everything seems to be working now.

**Comment by VerstandInvictus** [comment]
Confirmed, working for me as well now.
