### ISSUE TITLE
[experimental python] Local file inclusion

### ISSUE THREAD

**Issue by sephialife** [bigcompany/hook.io#184]
Hey guys, i just took an look and it seems that its possible to read local files using python.
I know its an experimental feature, here is the code i tested:
```python
import pprint
print "Hello, this is a Python script."
print "Hook['params'] is populated with request parameters"
pprint.pprint(open('/etc/resolv.conf','r').read())
```

**Comment by Marak** [comment]
I believe that `/etc/resolve.conf` is a file that has been specifically placed inside your `chroot` jail.

Are you able to enumerate or access any files which may cause any security issues? The shared application space *should* be read-only and contain no sensitive information.

**Comment by Marak** [comment]
Since we don't disallow reading the local files from the chroot jail, I'm going to close this issue for now.

If anyone finds any sensitive system data that can be accessed from within a hook service, please let me know.

**Comment by pyhedgehog** [comment]
@sephialife, please join [discussion](https://github.com/bigcompany/hook.io/issues/236#issuecomment-271610555) important for python support.
