### ISSUE TITLE
Non scrolling bug

### ISSUE THREAD

**Issue by MrJoshFisher** [bigcompany/hook.io#185]
hello

Im using chrome Version 47.0.2526.111 (64-bit) on Mac 10.11.2 and when looking at the things if there are several of them you cant scroll down the list ends up scrolling the page instead.

![czr2uefwkaa5rea](https://cloud.githubusercontent.com/assets/8970358/12510801/61c463ce-c104-11e5-91ed-50765d47af6d.png)

**Comment by Marak** [comment]
What's up?

Have you confused this project with http://hookr.io/ ?

This is hook.io

**Comment by MrJoshFisher** [comment]
Ha sorry
