### ISSUE TITLE
blacklist subdomains

### ISSUE THREAD

**Issue by reimertz** [bigcompany/hook.io#187]
@Marak I tried to reach you through twitter, but I realized that github is a better medium since you answered my previous issue within 5 minutes. :)

You should check this out: https://twitter.com/reimertz/status/688876357267369984

It seems you forgot to blacklist several subdomains, so I reserved them for you.
Let me know if you want me to do.

**Comment by Marak** [comment]
Thanks! 

Subdomains are on a first-come-first basis. If you found a security risk that could disrupt services, please let me know.

Subdomains are subject to revocation by hook.io at anytime for any reason. Same goes for user accounts. 

Feel free to keep the subdomains for now. If you want to put up a landing page or something useful, please do so.
