### ISSUE TITLE
Set hook as private

### ISSUE THREAD

**Issue by reimertz** [bigcompany/hook.io#189]
I might be stupid, but I can't figure this one out. 

Can I get some guidance?

**Comment by kauegimenes** [comment]
@reimertz Paid accounts have the ability to set hooks to private. http://hook.io/pricing

**Comment by Marak** [comment]
Private hooks are in beta testing.

Should be available for the public soon.

**Comment by reimertz** [comment]
Thanks for pushing this @marak. <3
