### ISSUE TITLE
Duplicate /logout handler

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#195]
Which of logout handlers will be executed?
https://github.com/bigcompany/hook.io/blob/master/lib/server/index.js#L144
https://github.com/bigcompany/hook.io/blob/master/lib/server/index.js#L401

**Comment by Marak** [comment]
Hey, good catch @pyhedgehog!

Definitely a mistake. I believe express will use the last route mapped, so the second handler will apply.

I will fix this for sure. Thank you.
