### ISSUE TITLE
Questions regarding recent price bump

### ISSUE THREAD

**Issue by reimertz** [bigcompany/hook.io#198]
@Marak , regarding this:

 https://github.com/bigcompany/hook.io/commit/796769252c2dd39b890a492232e55e44ec22b710#diff-683d8d9ce418176e12404fcabff641eeR111

You have written 

> *Any of these plans may change in the future with no notice. Our goal is to maintain a fair pricing model. New features will be added and service classes may be adjusted.

so I think it's all good but I think it's fair that you mention it in the blog/release notes?

Also, it seems that my account is in a bad state now where it says that I have the "Basic Hosting Plan $5" but according to my hook page, it says that I need to have a payed account to be able to set my accounts as private. 

Final question, what will happen to those who bump their account mid-period? will they have to pay ~$15 one month?

**Comment by Marak** [comment]
@reimertz -

Give me an hour so and I'll respond. 

I still have to run the migration script to enable paid status for all legacy paid accounts.

FYI, all users who signed up for the $5 plan will remain on that plan. No price increase for previous customers.

**Comment by Marak** [comment]
@reimertz - I manually set your account to paid right now.

If you log out / log back in, you should have access to the new private services.

**Comment by reimertz** [comment]
> Give me an hour so and I'll respond.

No sweat, don't stress it! Whenever you have time. 

> FYI, all users who signed up for the $5 plan will remain on that plan. No price increase for previous customers.

say fu**in what? That's awesome. :) I guess it pays off being an early adopter. :grinning: 

> @reimertz  - I manually set your account to paid right now.
Best. Service. Ever.

**Comment by Marak** [comment]
I've run the migration script and all users who already paid have had their `User.paidStatus` property set to `paid`.

I have written up a blog which talks about the new features: https://hook.io/blog/role-based-access-control

Was planning on doing a mailing list blast tonight.

I apologize if the roll-out of these updates caused any concern ( or any possible technical issues moving forward ) . We are still a one-man shop ever here and adding Roles is a huge cross-cutting change. I don't have the luxury of doing as much community management as I should be doing.

Doing my best to continue to test today and make sure the services are healthy.

Please let me know if / when you find any issues with the new release. The best place to understand how the new APIs work is by reading the new tests @ https://github.com/bigcompany/hook.io-test/tree/master/tests/client

Thank you for the continued feedback.

**Comment by Marak** [comment]
@reimertz - FYI, we now have a working Docker image, should you decide to do any local development.

Should make getting starting with a local hook.io very easy.
