### ISSUE TITLE
paid for basic hosting, still not allowed to make private hooks

### ISSUE THREAD

**Issue by tencherry10** [bigcompany/hook.io#208]
Hi,

Why is it that I am not allowed to make private hooks even after I paid for hosting plan? Under service security, the private service radio box is grayed out and blocked. And there is still the message: "In order to enable private services, you must upgrade to a paid account."

Thanks,
Terry

**Comment by Marak** [comment]
What's the account name?

You may have to log out / log in.

**Comment by Marak** [comment]
I found the account. Seems to be a bug with not updating the status after payment.

I've adjust your account to paid.

If you logout / login it should work. I'll get this fixed soon.

Thanks for the support!

**Comment by Marak** [comment]
You can also rename your account at https://hook.io/account to get a better url.

**Comment by tencherry10** [comment]
Hi @Marak 

Thanks for the quick response. It is working now.

I also renamed the account as you recommended.

Damn that's some fast support. 

I will close the bug now. Thanks again.

Terry

**Comment by Marak** [comment]
Sorry for the bug.

Re-opened issue until I'm able to resolve it with a commit and deploy.

Please feel free to open up more issues if you have any questions.

**Comment by Marak** [comment]
I've confirmed the issue [here](https://github.com/bigcompany/hook.io/blob/master/view/billing.js#L34) and will fix over the weekend.

I wasn't testing this very well before with the Stripe test gateway. I'll do a better job this time.

High priority.
