### ISSUE TITLE
Domain available for sale?

### ISSUE THREAD

**Issue by rahilj** [bigcompany/hook.io#211]
We are interested in hook.io. Available for sale?

**Comment by Marak** [comment]
Sure. Asking price is $3,000,000 USD.

**Comment by rahilj** [comment]
Thanks Marak, we will pass for now.

*Rahil Jain*
Graduate Student, University of Washington
Hardware Lead, Hook www.gethook.io
linkedin.com/in/rahilj

**Comment by Marak** [comment]
Was that too low?

I'm willing to go as high as $5,000,000
