### ISSUE TITLE
Paying for lost account

### ISSUE THREAD

**Issue by hnrc** [bigcompany/hook.io#214]
Yo :wave: 

We just discovered that we're being charged $50 every month for Hook.io but have apparently lost our account credentials (or it might belong to someone who's no longer working with us) :scream_cat:.
How can we sort this out? 

Please email me at henric.englund@schibsted.com

Cheers! :beers:

**Comment by Marak** [comment]
Responded over email. Sorry for the delay.

We'll sort it out. If you aren't using the account we can cancel / refund.
