### ISSUE TITLE
Paid but billing info saying it's unpaid.

### ISSUE THREAD

**Issue by Galeforce1** [bigcompany/hook.io#215]
I received an email receipt, but nothing about logging in, so created an account with the same email address, but it says 'unpaid'

**Comment by Marak** [comment]
Sorry about that.

If you provide me the account name I'l activate it for you.

**Comment by Galeforce1** [comment]
william-peepulprojects-com

thanks

**Comment by Marak** [comment]
I have activated the account.

You can login / logout to see the change.

Sorry for the issue.

**Comment by Marak** [comment]
Tracking #208

**Comment by Marak** [comment]
You can also rename your account at https://hook.io/account

I'd recommend doing this before creating any hooks. You'll get a better URL for your services.

**Comment by Galeforce1** [comment]
Thanks, Marak.
