### ISSUE TITLE
How to update hook source using the API

### ISSUE THREAD

**Issue by zanona** [bigcompany/hook.io#221]
I am trying to find how to update a hook via the API however I can't find anything related to it?
I can see that to create a new one I should use https://hook.io/new and provide data as [per the tests](https://github.com/bigcompany/hook.io-test/blob/b0ed187b57a095de6c9bd98316ed8bde22edaa5c/tests/client/hook-private-test.js#L56-L62) however I couldn't find information about the update endpoint? apparently `hook.io/update` won't work?

Thanks

**Comment by Marak** [comment]
That's my fault.

I let the test suites and `master` repo get ahead of what is actually deployed to production. This functionality is available, just not pushed live yet.

I have to push out a deployment which includes a bunch of API updates and release of `hook.io-sdk`. It's been sitting on the `master` branch on Github for a few weeks now. Sorry about that.

Finally have some time in the next week or so to push on deployments, so I will.

**Comment by Marak** [comment]
You should be able to update source for existing hooks via the `/admin` page

https://github.com/bigcompany/hook.io/blob/master/view/admin.js

**Comment by Marak** [comment]
This should now be possible with SDK.

Here is code example: https://github.com/bigcompany/hook.io-sdk/blob/master/examples/hook-update.js
