### ISSUE TITLE
API Rate Limit When Trying to Access Hook Source

### ISSUE THREAD

**Issue by matthewkinsa** [bigcompany/hook.io#224]
Not valid JSON: {"message":"API rate limit exceeded for Marak.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

**Comment by Marak** [comment]
Duplicate #203

**Comment by Marak** [comment]
Currently solution is to move your service into "Production" mode, as it should have already been set to.

Or you can move the code from gist directly into the hook.io system instead ( recommended )

**Comment by matthewkinsa** [comment]
Thanks, will this affect hook URLs?

**Comment by Marak** [comment]
What? You should really reach out to the person who setup these services for you.

I've already spoken to them and gave them information on how to resolve this.
