### ISSUE TITLE
Recipe for production deployment?

### ISSUE THREAD

**Issue by jmatsushita** [bigcompany/hook.io#225]
Hi there,

I'm completely new to hook.io and very interested. I saw your note on the README about not using Docker in production but... What are you using in production? Are you able to share more about your infrastructure?

Thanks!

Jun

**Comment by Marak** [comment]
@jmatsushita 

I'm glad to share, but I don't have much in formally prepared materials.

The short of it is that we are currently using a single load balancer with an elastic worker pool.

load balancer is for session management and reverse proxying requests to worker pool.

in the very near future we'll be switching to round-robin DNS load balancing across an elastic pool of front-end load balancers.

infrastructure is based off running `bash` scripts remotely over `ssh`. was using my own tooling for some time, have now been working on a fork of https://github.com/shipitjs/shipit

if you have any specific questions i'd be glad to answer.

if i may ask, what is your general interest in the project? are you looking to contribute or perhaps setup your own hook.io instance? we've got some interesting features coming out in the next few months.

**Comment by jmatsushita** [comment]
Hi @Marak thanks a lot for the reply. It is helpful and I just wanted to get a sense of what a production deployment would look like.

I'll let you know if I have more specific questions.

Of course, I'm happy to share what my interest is. Right now I am trying to kick the metaphorical tires of hook.io to get a sense of the project. I came at it with a very simple use case which is to store the result of an HTTP POST from a simple email registration form. And given that as a principle, we generally adopt open source software we can run on our own servers (which makes even more sense given the non user-encrypted data store), I thought I'd see how simple that would be. We might have other applications down the road as we're generally interested in the micro-service approach (in process of adopting it for a starting project).

With regards to contribution, if we end up adopting it, then it's possible we'll contribute. In any case, I'll at least continue posting (hopefully useful) issues when I bump into them. And also happy to let you know about my experience in adopting hook.io.

**Comment by Marak** [comment]
Yeah, our priority is supporting our paid users and improving the platform's features.

I can't do much in providing you help setting up your own production instance unless it was directly benefiting our paid users or improving the platform's features.

A lot of the developers who have contributed code to the platform has done so outside of the main repo ( in one of our many sub-dependencies )
