### ISSUE TITLE
PHP Timezone database corrupt

### ISSUE THREAD

**Issue by mrkwanzaa** [bigcompany/hook.io#231]
The php timezone database isn't working. Here is my exact error message.

`PHP Fatal error:  strftime(): Timezone database is corrupt - this should *never* happen! in /bin/run-hook-php(43) : eval()'d code(82) : eval()'d code on line 1`

**Comment by Marak** [comment]
Based on some quick googling, looks like a simple fix: http://stackoverflow.com/questions/8751221/php-timezone-database-is-corrupt-error

Since `php` is running inside a `chroot`, we need to give it access to this.

I'll see if I can hot-patch the server tonight.

**Comment by mrkwanzaa** [comment]
@Marak It still appears to be an issue. Any progress?

**Comment by Marak** [comment]
@mrkwanzaa Try now?

**Comment by Marak** [comment]
If not work, please send link to service with error. I will look later tonight. Thanks!

**Comment by mrkwanzaa** [comment]
@Marak Sorry, I wasn't able to test it until now, but works great. Thanks!

**Comment by Marak** [comment]
Awesome! Sorry for the delay. Please let me know if there is anything else we can do to improve PHP support.
