### ISSUE TITLE
Metadata views garbaged by hook processing

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#234]
Both:
 * https://hook.io/marak/image/rotate/source
 * https://hook.io/marak/image/rotate/resource

Attempts to run hook instead of show metadata.

**Comment by Marak** [comment]
Those are old examples and I should delete them. They have invalid names. `/` is no longer allowed in hook name.

**Comment by pyhedgehog** [comment]
Then there are another bad example: There are two `view` entries on https://hook.io/marak/ page.

**Comment by Marak** [comment]
I have to update the image examples. Issue is related to some old examples which allowed `/` as part of name.

Need to update this to our the new routing params API.

**Comment by Marak** [comment]
@pyhedgehog - Where are you finding these examples?

The examples for hook.io are available at hook.io/examples

`marak/view` isn't broken. You just aren't using it for it's purpose. It's a hook I'm using for something else.

**Comment by pyhedgehog** [comment]
Thanks for reference. I'll continue in bigcompany/hooks#1
