### ISSUE TITLE
Account verification problem

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#239]
Last week I'm facing following warning on all admin pages:

```
Attention: Please verify your account with an email address.
Without an email address on record, it's possible you may get locked out of your account.
```

If I attempt to enter my email (same as specified in my account) I have several hours of peace and then warning appears again.
My account name: `pyhedgehog`
My email: `pywebmail@list.ru`
My account provider is GitHub.

Last mail from hook.io domain was at 1 March from `hookmaster@hook.io` titled `hook.io - Role Based Access Control. API Access Keys. ES7`.

**Comment by Marak** [comment]
Yes, sorry about that.

It's for github sso. I have a fix locally already.

Will try to deploy soon.

**Comment by Marak** [comment]
This should be resolved and deployed for some time now.

Sorry for late update.
