### ISSUE TITLE
hpm server down (npm deploys not working)

### ISSUE THREAD

**Issue by mikaelkaron** [bigcompany/hook.io#241]
On the public instance hook.io try a simple hook like this:

```javascript
module["exports"] = function(hook) {
  var select = require("json-select/select");
  hook.res.end("end");
};
```

when testing the result is:

```
module.js:338
    throw err;
          ^
Unable to communicate with hpm server 

connect ECONNREFUSED
```

**Comment by Marak** [comment]
Sorry about that. We've been upgrading server security and infrastructure
lately.

The `hpm` service was attempting to connect to local redis without any
authentication ( which is no longer allowed )

I updated the configuration to use the new password and restarted hpm. I
also installed `json-select` package. Should be working again.

The current approach to NPM deps isn't great. We need to setup a ghost
registry to all published deps are just automatically available and
installed.

**Comment by mikaelkaron** [comment]
It is indeed working now.

**Comment by Marak** [comment]
Sorry for the trouble. Please let me know if you run into any more issues or have any questions.
