### ISSUE TITLE
Ability to remove account

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#242]
As I'm stuck with issue #237 I've decided to recreate account anew and found that there are no way to remove account (I can only rename it, but I'm unsure if there are plans to force email uniqueness).

**Comment by Marak** [comment]
I have same issue blocking setup / teardown of integration tests.

We'll need to make super admin user role that can delete user accounts. Is only safe way.

Should be resolved soon.

**Comment by Marak** [comment]
We have a super admin ability to remove accounts, but I'm not sure I want to expose the ability for users to delete their own accounts. Could be dangerous.

**Comment by Marak** [comment]
I've created the ability for a super admin role to delete accounts for testing and local development, but I'm not going to expose this endpoint to users. It's just not a great idea for now. 

I'll take a look at #237 and see exactly why we can't delete the offending hooks. I'm guessing recent improvements to API will prevent this case from happening again and we are dealing with legacy data.

Closing.
