### ISSUE TITLE
Security issue with cron

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#244]
As report contains sensitive data it was send directly to Marak via gitter.

**Comment by Marak** [comment]
Am I on Gitter?

You can email support@marak.com

**Comment by pyhedgehog** [comment]
> Am I on Gitter?

Yes.

> You can email...

Mail sent.

**Comment by Marak** [comment]
This should be resolved for some time. Not sure much a security issue, but user leaking own API to themself.
