### ISSUE TITLE
Invalid url https://hook.io/features referenced in menu

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#247]
https://github.com/bigcompany/hook.io/blob/386ebaf041bcac75ee29b8382b0de64af0d6c84d/view/layout.html#L209 and https://github.com/bigcompany/hook.io/blob/386ebaf041bcac75ee29b8382b0de64af0d6c84d/view/layout.html#L217 refers non-existant URL https://hook.io/features

**Comment by Marak** [comment]
Thanks @pyhedgehog.

Will be out in the next deploy.
