### ISSUE TITLE
Support for mschema in other languages

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#249]
Could it be configured on server level or should we use language/framework-specific things?

**Comment by Marak** [comment]
Great suggestion!

I believe adding schema support for all languages should be very easy. Is already configured to run on backend for all languages, just not enabled.

Related #205 #138 

I'd also like to also consider offering alternate modeling languages like GraphQL. Either way, users should be able to easily define schema for service regardless of language.

**Comment by Marak** [comment]
@pyhedgehog -

We've added mschema input parameter support for all languages.

You should be able to now set the schema for any service on it's `/admin` page. Everything should just work.

Please let us know if you run into any issues.
