### ISSUE TITLE
Can't read /services with api key

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#251]
I have a correct `$hook_private_key` but `/services` has no hooks listed:

``` console
$ python2.7 -m hookio keys checkAccess hook::view::read
{
  "hasAccess": true
}

$ python2.7 -m hookio account services

$ 
```

When I'm using `/login`, everything works fine:

``` console
$ hook_private_key= python2.7 -m hookio --login $hookio_login account services
pythonsdktest/80e2416a-a987-417c-bd65-7368eb43df31-5A9D9260-bug
pythonsdktest/80e2416aa987417cbd657368eb43df311609CA9Ebug
pythonsdktest/80e2416aa987417cbd657368eb43df312E1D7A5Ebug
pythonsdktest/BUG237test09
pythonsdktest/estABCDEFGH_bug237test08
pythonsdktest/hooktest
...
```

**Comment by pyhedgehog** [comment]
There are related problem - I haven't found how to get owner of key. Even worse - fake header `x-hookio-user-session-name` is `anonymous` for api requests.
I've checked that if `x-hookio-user-session-name` set in request it's ignored. But it's replaced by `anonymous` instead of key owner.

**Comment by Marak** [comment]
This appears to be resolved locally and working in the new version of SDK.

Will update / close this issue when the deployment is live.

**Comment by Marak** [comment]
Okay, the new role for listing / searching services is called `hook::find`.

Will continue to polish this and have it ready for next release.

**Comment by pyhedgehog** [comment]
Old internal keys (`{..., "name": "api-access-key", "key_type": "internal", ...}`) don't have `hook::find` role. Related to #243.

**Comment by Marak** [comment]
I will be sure to run a migration script which generates all new roles for the old internal keys.

Noted. Thank you.

**Comment by pyhedgehog** [comment]
Also `/keys` interface not yet has checkbox for `hook::find` role.|

**Comment by Marak** [comment]
That's fixed locally now.

**Comment by Marak** [comment]
Is auto-enumerated from resource definition.

**Comment by pyhedgehog** [comment]
And should we have another issue for request interface+API for editing existing keys.

**Comment by Marak** [comment]
Is refactored already.

see: https://github.com/bigcompany/hook.io/tree/master/view/keys

More tests I have locally.

Should work with JSON now.

We need to get docker or vagrant working for developers to do local dev...

**Comment by Marak** [comment]
Release is coming soon. Been very busy with `stack` refactor into hook.io.

**Comment by pyhedgehog** [comment]
Cool. `stack` is more important.

**Comment by Marak** [comment]
@pyhedgehog - Please check out `python` and `python3` binaries to see if we can integrate hook.io SDK 

If you can make single request work I can start to update with new APIs.

https://github.com/Stackvana/stack/blob/master/bin/binaries/python
https://github.com/Stackvana/stack/blob/master/bin/binaries/python3

**Comment by Marak** [comment]
Can also look at : https://github.com/bigcompany/hook.io-sdk/tree/dev

for reference. working the `dev` branch

**Comment by Marak** [comment]
@pyhedgehog 

I've completely revamped the API and keys API.

This should be resolved in production now.

Working API calls should exist for all endpoints here: https://github.com/bigcompany/hook.io-sdk/tree/master/examples

Please let me know if you still not able to read the data you need.
