### ISSUE TITLE
'Object.assign is not a function' under ES7

### ISSUE THREAD

**Issue by reimertz** [bigcompany/hook.io#254]

**Comment by Marak** [comment]
@reimertz - Can you confirm if this happens using `stack`?

 https://github.com/stackvana/stack

All `es7` / `babel` support should be handled in `stack` lib now. I'd make sure to use the latest public version on npm.

**Comment by Marak** [comment]
@reimertz -

This should be resolved now that we've updated Node.

try: 

  http://hook.io/marak/object-assign-test
  http://hook.io/marak/object-assign-test/_src

Thank you for the feedback!
