### ISSUE TITLE
req.connection.remoteAddress = localhost

### ISSUE THREAD

**Issue by reimertz** [bigcompany/hook.io#256]
Right now, the only way to get the remoteAddress is 

``` js
const ip = hook.req.headers['x-forwarded-for'].replace('::ffff:', '')
```

**Comment by Marak** [comment]
Good catch!

I guess the least surprising behavior here is to override `req.connection.remoteAddress` to use the proxy IP value. It won't be the actual value ( since its being proxied around ), but for the user it should work.

Will fix and get out in the next release.

**Comment by Marak** [comment]
@reimertz -

This should be resolved with https://github.com/Stackvana/stack/commit/fab671a7b2205da554a7e42be4e2a4caea5948a1

I can't deploy this right now, but I'll make this sure is included in the upcoming release.

**Comment by Marak** [comment]
Resolved in production.

see: http://hook.io/marak/test-remote-address

Thanks again @reimertz !
