### ISSUE TITLE
Private hooks not shown in list of services

### ISSUE THREAD

**Issue by andrewtlove** [bigcompany/hook.io#257]
It looks like private services are unlisted until an action is performed that authenticates the user.  Do the following to reproduce:

1. Log in
2. Create new public service
3. Create new private service
4. Log out
5. Log in
6. _!! Private service is missing from list_
7. Delete public service from step 2
8. _Private service is now listed correctly_

**Comment by Marak** [comment]
That's odd. 

Probably a bug in the display code for services.

This might have already been resolved locally, will double check here.
