### ISSUE TITLE
hook.open not working

### ISSUE THREAD

**Issue by mikaelkaron** [bigcompany/hook.io#260]
I'm trying to do an outbound request like this:

```
hook.open('http://requestb.in/1jpte431');
```

but nothing is received on the other end.

**Comment by Marak** [comment]
@mikaelkaron 

For clarity and performance, I've removed `hook.open` from the API ( for now ).

Since it was just a wrapper around `hyperquest` module and only available for node, I figured it's best to just leave the require optional and up to the microservice script itself.
