### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by DLesage25** [bigcompany/hook.io#261]
Invalid certificate when trying to access  https://hook.io/login.

**Comment by Marak** [comment]
Ahh! SSL expired today, not sure how we missed that.

Going to renew the cert today in a few hours.

Sorry for the trouble.

**Comment by DLesage25** [comment]
Thank you!

**Comment by Marak** [comment]
Resolved.

Sorry about that. The emails for SSL renewal were going to a black hole.

I renewed the SSL and everything is working now.
