### ISSUE TITLE
Environmental Variable bug

### ISSUE THREAD

**Issue by Feanor878** [bigcompany/hook.io#262]
Hi there,
have found a little bug recently. When I add a new env. variable with value 30004500xxxxxxx236343033 ( 'x' are actual numbers 0-9, no symbols or any other characters), after I assign it a key name and save it, the value is changed from original 30004500xxxxxxxxxxx43033 to 3.0004500xxxxxxx23e+23

**Comment by Marak** [comment]
@Feanor878 

I have confirmed this issue on production.

The issue already appears fixed in our `master` branch and should be deployed within the week.

Will let you know when it's ready for testing.

**Comment by Marak** [comment]
@Feanor878 -

This should be resolved in production. Please let us know!
