### ISSUE TITLE
Endpoints and website are down

### ISSUE THREAD

**Issue by DLesage25** [bigcompany/hook.io#263]
Getting error in all endpoints:

Error communicating with worker http://worker2:10002/partnerhero/clock?text=shifts&email=daniel%40partnerhero.com

The streaming connection errored in recieving data.

Please copy and paste this entire error message to Support.

Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

and also website is completely down.

**Comment by Marak** [comment]
Sorry about that. We had a small amount of downtime with the CouchDB getting full again too quickly due to a user accidentally spamming the service.

I'm in final testing stages of a new version of hook.io which should be able to handle large amounts of traffic better much better.
