### ISSUE TITLE
Sign in with GitLab

### ISSUE THREAD

**Issue by LukeeeeBennett** [bigcompany/hook.io#271]
I'd love to see a `Sign in with GitLab` feature.

This will also require Font Awesome to be upgraded to `>= 4.6`. Currently `4.4.0`.

<img width="1011" alt="screen shot 2017-01-25 at 11 33 08" src="https://cloud.githubusercontent.com/assets/5678671/22289169/20e22ea2-e2f2-11e6-8f58-1c7993493e24.png">

**Comment by Marak** [comment]
Will accept PR for this.
