### ISSUE TITLE
Defaults in `mschema` not working

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#276]
Hook `https://hook.io/marak/echo` used to return `{"param1": "foo", "param2": "bar"}`. Not it returns `{}`. Seems `mschema` defaults not working.

**Comment by Marak** [comment]
@pyhedgehog -

I've been moving away from the `marak` name-spaced examples in favor of using https://github.com/stackvana/microcule-examples repo ( which is kept in sync with hook.io )

Have you tried testing input schemas on your own services?

https://hook.io/examples/javascript-input-schema appears to be working

**Comment by pyhedgehog** [comment]
In examples: [javascript-input-schema](https://hook.io/examples/javascript-input-schema) works, but [echo](https://hook.io/examples/echo) doesn't. Seems installation issue - javascript-input-schema contains separate file `schema.js`, but echo contains schema as embedded code (as before).

> Have you tried testing input schemas on your own services?
Not yet. Right now I have different goal.

**Comment by Marak** [comment]
Not sure what else you would expect.

`echo` isn't suppose to have schema anymore. If you look at the resource, you can see it's disabled: https://hook.io/examples/echo/resource

**Comment by pyhedgehog** [comment]
Ok, understood.
