### ISSUE TITLE
Using git inside of a microservice

### ISSUE THREAD

**Issue by mathisonian** [bigcompany/hook.io#278]
Is it possible to `git clone` something inside of a microservice? I'm trying to build something similar to https://bl.ocks.org/ that will take in the URL of a gist, and return the contents one of the files. In particular I'd like to be able to use http://www.nodegit.org/ or similar

**Comment by Marak** [comment]
Absolutely!

I think the best thing to do would be use https://www.npmjs.com/package/octonode library ( which should be installed and ready to go on hook.io )

To give you an idea on how to do it, we actually are doing this same type of functionality internally ( fetching source code from files in a gist ) using this: https://github.com/Stackvana/microcule/blob/master/lib/plugins/sourceGithubGist.js#L45 

You'd just need to create a new JavaScript service which used `octonode` ( or any other Github API wrapper ), call the Github API, and pipe the response back to the client.

Hope that helps.

**Comment by mathisonian** [comment]
Awesome, thanks @Marak!
