### ISSUE TITLE
Error logs showing up in revision history

### ISSUE THREAD

**Issue by samhavens** [bigcompany/hook.io#280]
Not sure if this is expected behavior?

![image](https://cloud.githubusercontent.com/assets/7231205/24416645/57612522-139a-11e7-882d-02ca6722e8f0.png)

**Comment by Marak** [comment]
It looks like it's running some custom user code which is crashing.

It looks like that error stack is coming from the user-defined service code ( which is trying to reference item 0 from a `null` value ) ?

**Comment by samhavens** [comment]
Yes, that is the cause of the error, but I was confused that the message was showing up in `_rev` instead of the logs. Should I do something like

```js
process.on('uncaughtException', (error) => {
   console.log(error.stack);
});
```
to make the error show up in the logs?

**Comment by Marak** [comment]
Not sure what else you would expect the error to do?

It looks like it's throwing an uncaught error, that is going to cause a crash no matter what you do.

**Comment by samhavens** [comment]
I realize that an uncaught exception will cause a crash... I guess I am just confused about why the error stack shows up in revision history instead of the logs.

**Comment by Marak** [comment]
The logs will only store information that is put there via `console.log`.

Uncaught errors get piped back to the client. Are you seeing a different behavior then that? Revisions should be working the same as regular services.

**Comment by Marak** [comment]
I think the confusion here is that the revision being loaded had an error in the code, and when you attempted to run that error'd revisioned it spit the error back to the browser.

I don't think you were seeing error logs, but the actual result of the old revision running again.

We should probably add better UX on the _rev page to allow for showing both source code or running the previous version.
