### ISSUE TITLE
Error in concurrency hit logic

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#282]
All my services (i.e. https://hook.io/pyhedgehog/static) returns `Rate limited: Max concurrency limit hit: 10`
And https://hook.io/metrics/pyhedgehog/running returns 10.
However there are no long-running services.

**Comment by Marak** [comment]
Try again?

**Comment by pyhedgehog** [comment]
Thank you!

**Comment by pyhedgehog** [comment]
Once again.

**Comment by Marak** [comment]
I again reset your limit.

There must be a bug somewhere causing the limit to occasional not decrement.

We need to identity the bug, but also add a mechanism in order to occasionally check and reset the tally ( in case of misreported opened hooks ).

**Comment by pyhedgehog** [comment]
Once again. I have no idea which hook triggers this error. Any ideas?

**Comment by Marak** [comment]
I reset again. Odd.

Have you changed anything recently? It could be error in service not ending.

If not, it could be due to process crash causing counter to miss decrement.
I'll investigate more this weekend.

**Comment by pyhedgehog** [comment]
Once again.

There are no my hooks running according to [ps](https://hook.io/marak/gateway-bash?source=ps%20-ef).

**Comment by Marak** [comment]
Reset again.

I'm working on a new patch to improve metrics.

It would help if we had some idea of which hook was causing count to not decrement.

**Comment by pyhedgehog** [comment]
Once again. I've wrote [gatherhits.py](https://gist.github.com/pyhedgehog/1cb34848ae46aad1bc1687df5dd5f73f) and discovered that it's [hooklog](https://hook.io/pyhedgehog/hooklog/source) service causing problem (as it's only touched). I see no "open" (i.e. without `hook.res.end`) branch.

Now it was failed somewhere between 18:00:58 and 18:02:14 GMT.

**Comment by pyhedgehog** [comment]
Once again. I've changed `hooklog` - need to check.
But this is bug anyway - following code will lead to this error:
```javascript
module['exports'] = function(hook) {
  # not hook.res.end() will lead to concurrency limit error
}
```

**Comment by Marak** [comment]
Okay this is good. It means issue is because of timeout not reseting concurrency count.

That is odd, because we should have code to handle that case. Regardless, I will now write tests for concurrency using this example and ensure there is fix. Thank you.

I have also added the ability for users to manually reset their own limits in the UI / API. This will allow user to immediately get reset limit, but also send email to admin with users information.

**Comment by Marak** [comment]
I've made test coverage for account usage limits and concurrency.

https://github.com/bigcompany/hook.io/blob/master/tests/client/account-usage-limit-test.js

Functionality appears to be working in `master`, so I suspect issue is resolved locally. I will push update very soon to production and continue to test.

What is odd though, is that I can test on production with hook that never responds and my running metric decrements properly after service timeout. Perhaps there is another error in system.

**Comment by Marak** [comment]
I've made some improvements and am working on improving this situation so it will stop happening.

If for some reason your account gets locked again, you can instantly reset limit here: https://hook.io/account/unlock

Will be adding more analytics and metrics to the UI to display current usage.

**Comment by pyhedgehog** [comment]
Cool.

**Comment by Marak** [comment]
Closing for now.

We'll be following up with better analytics for running services.
