### ISSUE TITLE
HTTP PUT or DELETE on my hook timeout or return not found

### ISSUE THREAD

**Issue by simocl** [bigcompany/hook.io#283]
Hello,

HTTP GET and POST work fine. Is there something to do to have the PUT and DELETE working?

I used the curl command to my hook. My hook just returns the params received. 

Can someone help me?

Thanks

**Comment by Marak** [comment]
@simocl -

Sorry about that, we must have lost the `PUT` and `DELETE` verbs awhile back when refactoring load-balancer.

I've added new test coverage and fixed the issue. Should be working again.

Please let me know if you have any more issues.
