### ISSUE TITLE
Trying to login with Hook.io Client SDK

### ISSUE THREAD

**Issue by locohost** [bigcompany/hook.io#287]
I'm in cmd (admin) console, I type hook login and get the following. What step am I missing?

{ Error: connect ECONNREFUSED 127.0.0.1:9999
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9999 }

**Comment by Marak** [comment]
That seems like it's using the dev config information ( localhost port 9999
).

How did you install the sdk? Are you able to update the configuration to
use production configuration?

This may help:
https://github.com/bigcompany/hook.io-sdk/blob/master/config/production.json

**Comment by locohost** [comment]
I used npm in the cmd console to install. I did **hook config -myrealkey-** but other than that and **list** I don't see what else I can do with config. How do I _update the configuration to use production configuration_? I'll check the link you provided now. Thank you for helping! :-)

**Comment by locohost** [comment]
Ok in C:\Users\mdeibert\AppData\Roaming\npm\node_modules\hook.io-sdk\config my production.json file looks like this...

`{
  "host": "hook.io",
  "port": 443,
  "protocol": "https://",
  "uri": "https://hook.io",
  "location": "/Users/a/dev/big/hook.io-sdk/config/production.json",
  "env": "production"
}`

**Comment by locohost** [comment]
I also tried installing without the -g flag to put the node folder local. production.json looks the same. In either case, I get this when I do **hook login**, then past my key...

checking role access...
{ Error: connect ECONNREFUSED 127.0.0.1:9999
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9999 }

**Comment by Marak** [comment]
I'll double check the package to see what's going on, but based on your messages it's still using the local dev configuration. You need to update the config to use the production config ( not local host ).

**Comment by locohost** [comment]
How do I _update the config to use the production config_?

**Comment by Marak** [comment]
I think it might be using the dev mode by default, what happens if you set your `NODE_ENV` to production? Check out https://github.com/bigcompany/hook.io-sdk/blob/master/config/index.js#L11

I think the default setting might be wrong in the sdk, should still be an easy fix.

**Comment by Marak** [comment]
Did you try running:

hook config production

**Comment by Marak** [comment]
Although that command might not be available yet in the last published package. Let me know if you can figure out how to load the right config. It should be a very simple change.

I'll see what I can do about switching the sdk to use production config by default.

**Comment by locohost** [comment]
I enter **hook config help** and I don't see an option for setting environment so I wouldn't know to try that.  The only options I see are **key**, **list** and **help**. Yeah it looks like the default environment is dev.

**Comment by Marak** [comment]
Environment variable is in your shell or command prompt environment, not in the SDK itself. The SDK reads this value.

Not much else I can do for you. I'll release a new version of the SDK which uses production config as default value which may help.

It's all there, you are one line away from making it work on your machine.

**Comment by locohost** [comment]
Yes it's working. Thank you for all the help :-)

**Comment by Marak** [comment]
New version of `hook.io-sdk@3.2.0` is now released and should have better defaults and options for SDK env.
