### ISSUE TITLE
hook deploy erases my route

### ISSUE THREAD

**Issue by locohost** [bigcompany/hook.io#288]
I'm using hook.io-sdk to deploy my services from local. I can set a specific route in the web UI like `/:model` and then test the service and it works great. But then every time I **hook deploy ...**, my route is erased. What am I doing wrong? Thanks :-)

**Comment by Marak** [comment]
Could be a bug, I will investigate and see if I can confirm it.

FYI, it would be best to file SDK related issues in the SDK repo here: https://github.com/bigcompany/hook.io-sdk

Thanks for your feedback.

**Comment by locohost** [comment]
I will post any other SDK related issues in hook.io-sdk. Thanks for taking a look at this.

**Comment by Marak** [comment]
I've confirmed the issue and have pushed an update to production.

Fix seems to be entirely on the back-end.

Thanks again for your feedback.
