### ISSUE TITLE
Link to calling hooks gives 404 error

### ISSUE THREAD

**Issue by locohost** [bigcompany/hook.io#289]
On page: https://github.com/bigcompany/hook.io, about half way down, there is a link: **easily call other Hooks**, it tries to link to: **https://hook.io/Marak/merge** but gives 404 error.

I reeeeeeally need to see the correct way to call a hook from within a hook. Right now I'm using https.get which cannot be the right way to do this. If we had a hook.io forum, I could post my questions and code there for comments and help :-)

**Comment by Marak** [comment]
I'll have to update the ReadMe to point to the new locations.

Check out: http://hook.io/examples

Also: https://hook.io/examples/javascript-stream-merge/source

**Comment by locohost** [comment]
Ok so looking at that link, maybe I'm close to doing this right. Here is my current code. I calls 2 external hooks, 1 for jasonwebtoken processing and then a generic hook that returns all records from a MongoDb. 

How terrible is this?...

```
module['exports'] = function myHook(hook) {

    const request = require('request');
    const url = 'https://hook.io/locohost';
    let req = null;
    let token = hook.req.headers.authorization;
    if (token != null) {
        token = token.split(" ")[1];
        request.get(url + '/jwt/verifytoken?token=' + token, (err, res, body) => {
            if (err) {
                return hook.res.end('jwt request error: ' + err.message);
            } else {
                body = JSON.parse(body);
                if (body.issuer) {
                    request.get(url + '/any-model/' + hook.req.params.hook, (err, res, body) => {
                        if (err) {
                            return hook.res.end('any-model request error: ' + err.message);
                        } else {
                            return hook.res.end(body);
                        }
                    });
                } else {
                    return hook.res.end('Invalid token');
                }
            }
        });
    } else {
        return hook.res.end('Invalid token: Token is null');
    }

};

```

**Comment by locohost** [comment]
Above code is working, I just want to call other hooks correctly :-)

**Comment by Marak** [comment]
That is pretty good. Hooks are just HTTP streams.

We also have a new API coming soon that will allow hooks to be chained together as HTTP middlewares.

**Comment by locohost** [comment]
Each request.get makes the final response return slower and slower. Which is to be expected. I may have to drop the second req.get and just put MongoClient in each service. At some point I want to try your datastore. I imagine that would speed up the requests significantly.

Thanks for looking at the code. As usual, thanks for the help :-)
