### ISSUE TITLE
Seems cron not working since 2017-11-30T20:00:58.997Z

### ISSUE THREAD

**Issue by pyhedgehog** [bigcompany/hook.io#309]
Date got from https://hook.io/marak/testcron/logs.

**Comment by Marak** [comment]
Cron services have been rebuilt as first class API citizen and should be working again. Creating a cron is now decoupled from creating hook.

see: https://hook.io/cron

Will be looking to improve this ( there is a bit of commented out functionality for advanced cron options ).
