### ISSUE TITLE
Not working locally

### ISSUE THREAD

**Issue by takeerdevs** [bigcompany/hook.io#322]
after running docker-compose up, did its thing and gave me a url as http://localhost:9999 but when i access, keeps looping between login and account/expired..
I am running docker in MacOs High Sierra.
![nwl](https://user-images.githubusercontent.com/49426357/61501809-abfd1c80-a9d9-11e9-8230-7ad2c4b4f3e8.png)

**Comment by takeerdevs** [comment]
Solved it.. ..

**Comment by JokerQyou** [comment]
Hi, may I ask how did you manage to solve this issue? I seem to have ran into the same problem.

**Comment by AmreeshTyagi** [comment]
> Solved it.. ..

@takeerdevs I am also facing same issue. Please let me know, how you fixed it.

**Comment by AmreeshTyagi** [comment]
Solved it by changing date at line number 155 in view/layout.js to new date.
` var created = moment('4/2/2020');`
