### ISSUE TITLE
Problem with service "message": "Rate limited: Max concurrency limit hit: 4"

### ISSUE THREAD

**Issue by EvgeniyVorobev** [bigcompany/hook.io#325]
Hello Marak ! I have plan Premium , login evgggordadym@gmail.com but have an error 
>  "message": "Rate limited: Max concurrency limit hit: 4" 
Please reset limit for account! Thank you! Waiting for your reply as soon as possible.

**Comment by Marak** [comment]
Should be resolved now, I think you put an extra g in that email, it took a moment to find the account.

**Comment by EvgeniyVorobev** [comment]
> Should be resolved now, I think you put an extra g in that email, it took a moment to find the account.

hello again, the saim problem. account evggordadym@gmail.com , please reset limits, thanks!

**Comment by EvgeniyVorobev** [comment]
@Marak hello again, the saim problem. account evggordadym@gmail.com , please reset limits, thanks!
