### ISSUE TITLE
hook does not allways use latest version

### ISSUE THREAD

**Issue by piffie** [bigcompany/hook.io#34]
Hi,

when i go back in the browser and press run again (in debug theme) than it does not allways use the latest version. Sometimes it seems to run a old one, presenting me an old error.

**Comment by Marak** [comment]
It's possible you could be copying and pasting the wrong link from Github Gist causing the wrong revision to load.

It's also possible there is an error somewhere in the hook and theme caching code.

Can you provide a reproducible case showing this error happen? I haven't seen this in testing yet, but I have made the mistake of using the wrong Gist link before ( causing old code to run). It might be easier if you setup a local version of hook.io for testing.

**Comment by Marak** [comment]
@piffie -

I found and fixed an issue where Hook theme presenters were getting module cached, but found no issues in caching of source code for hooks.

After some observations I believe that Github is returning a cached version of the document. I can compare the version pulled onto the server versus the version pulled from the website to my browser and see two different documents.

The current work-around is to wait a few moments for Github to update their cache. It's possible if we authenticate the request to Github we might get the fresher version of the document.

**Comment by Marak** [comment]
Okay, I am seeing this a lot today. It's really annoying waiting for the source code to update.

Will investigate how to get Github to always return the latest version ( and not a cached version )

**Comment by Marak** [comment]
The issue appears to be coming from fetching the raw gist from github's www server instead of their gist api. This means sometimes we are getting a cached version from github.

Updating to use the correct gist api endpoint should resolve this.

**Comment by Marak** [comment]
@piffie - This should be resolve in production now.

Please let me know if you see the issue come up again.

Thank you for your feedback!
