### ISSUE TITLE
seems to be down

### ISSUE THREAD

**Issue by JamesKyburz** [bigcompany/hook.io#35]
Getting error "error happened in your connection" on all hooks.

**Comment by Marak** [comment]
Ran out of HD space the other day ( due to large log files ).

Rotated the logs and restarted all processes.

Must have missed restarting the couchdb instance. Everything should be working now.

**Comment by JamesKyburz** [comment]
nice!

James Kyburz
Cell: +46 734 448489 | Google Talk: james.kyburz | Skype: james.kyburz
http://twitter.com/jameskyburz
