### ISSUE TITLE
Add xml2js and aws-sdk to hook.io support?

### ISSUE THREAD

**Issue by LusciousPear** [bigcompany/hook.io#38]
Hi! I need to do some mucking about with AWS, could you add xml2js and aws-sdk?

**Comment by Marak** [comment]
Yes, we can easily add those.

The best way to add new modules is to perform a pull request to https://github.com/bigcompany/hook.io/blob/master/modules/modules.js so we know the correct versions you require.

**Comment by Marak** [comment]
`xml2js` and `aws-sdk` latest have both been installed to production.

Let us know if you require any more modules and feel free to put them together in a pull request.

Thanks!

**Comment by LusciousPear** [comment]
Thanks! xo

On Wed, Mar 4, 2015 at 12:44 PM, Marak <notifications@github.com> wrote:

> xml2js and aws-sdk latest have both been installed to production.
>
> Let us know if you require any more modules and feel free to put them
> together in a pull request.
>
> Thanks!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bigcompany/hook.io/issues/38#issuecomment-77243156>.
>



-- 
Bradford Stephens
Freelance CTO & Startup Exec
22acacia.com
(530) 763-DATA
