### ISSUE TITLE
How to POST data to another URL

### ISSUE THREAD

**Issue by lylepratt** [bigcompany/hook.io#39]
I'm doing some experimentation with hook.io. I assumed I would have access to something like the `requests` api, but all I see is a method called `hook.open` in the documentation but that appears to open a stream, when I just want to fire off an HTTP request. I'm just trying to proxy some data from one API to another after manipulating it a little. Am I missing something obvious?

**Comment by Marak** [comment]
You should have access to `request` module, `hyperquest` module, and node's built in `http` module.

As documented, `hook.open` is an alias to `hyperquest` module.

Here is an example using node's built in http request method for making a simple request.

https://gist.github.com/Marak/95403b36b297d5e6bdb0#file-isthewebsitedown-js

The key take-away is that you can use any npm module you need. Here is a partial list of supported modules: http://hook.io/modules. You can add additional modules by performing a pull request to this repo.

**Comment by lylepratt** [comment]
Many thanks! Didn't realize I could require modules :) just totally overlooked that.

**Comment by lylepratt** [comment]
Hi, I started testing my hook from the Hook.io webpage, but am receiving this error, even if I completely remove the `auth` option. It seems to be stuck:

```
Error: auth() received invalid user or password
    at Request.auth (/home/ubuntu/hook.io/node_modules/request/request.js:1530:11)
    at Request.init (/home/ubuntu/hook.io/node_modules/request/request.js:551:10)
    at new <anonymous> (/home/ubuntu/hook.io/node_modules/request/request.js:282:8)
    at /home/ubuntu/hook.io/node_modules/request/index.js:50:10
    at Function.<anonymous> (/home/ubuntu/hook.io/node_modules/request/index.js:80:27)
    at /home/ubuntu/hook.io/temp/lylepratt/76e491486df331a09a5f.js:24:11
    at /home/ubuntu/hook.io/lib/resources/hook/runUntrustedHook.js:154:5
```

**Comment by Marak** [comment]
The best thing to do is the post the gist of the hook you are trying to create so we can better see what the issue is. Are you attempting to make an http request to another website that requires auth?
