### ISSUE TITLE
Hook error when gist no longer available

### ISSUE THREAD

**Issue by vrunoa** [bigcompany/hook.io#44]
Hey @Marak I found an error testing an old hook I was using to test this module. I believe the module crash when the gist is no longer available. Maybe it would we good to avoid this exception and show a pretty message? Let me know and i'll try to merge a PR with a fix.

```javascript
//output
/root/hook.io/temp/vrunoa/560bb84d38e24078b66a.js:1
(function (exports, require, module, __filename, __dirname) { <!DOCTYPE html>
                                                              ^
SyntaxError: Unexpected token <
    at vm.js:73:16
    at Module._compile (module.js:443:25)
    at Object..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.<anonymous> (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.attemptToRequireUntrustedHook (/root/hook.io/lib/resources/hook/attemptToRequireUntrustedHook.js:18:21)
    at /root/hook.io/lib/resources/hook/runHook.js:22:11
    at /root/hook.io/lib/resources/hook/fetchHookSourceCodeFromGithub.js:43:13
```
[http://hook.io/vrunoa/echo](http://hook.io/vrunoa/echo)
[https://gist.github.com/vrunoa/560bb84d38e24078b66a](https://gist.github.com/vrunoa/560bb84d38e24078b66a)

**Comment by Marak** [comment]
Thank you @vrunoa 

A PR would great.

**Comment by Marak** [comment]
@vrunoa - I see you have made a new branch. 

Any updates on the fix for this? 

Starting to roll out new releases and would like to include this fix.

**Comment by vrunoa** [comment]
Sorry @Marak , i've started creating a fix but didnt have the time to finish it. This weekend i'll make you a PR with a fix.

**Comment by Marak** [comment]
Gracias mi amigo!

**Comment by vrunoa** [comment]
Hey @Marak sorry I could'nt close this issue. Is this already fixed ? Otherwise I could take a look.

**Comment by Marak** [comment]
I'm not sure. I've made a few updates to error handling.

Feel free to test it out again on the live site and see what happens?

**Comment by vrunoa** [comment]
mmm, on [http://hook.io/vrunoa/echo](http://hook.io/vrunoa/echo) i'm getting
```bash
Error communicating with worker 10001

Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:293:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

This might be a new error. I'll update my repo with the last version and take a look.

**Comment by Marak** [comment]
I just tried locally and it seems to be resolve here. I'll check production after the next update, I bet it's fixed....

**Comment by vrunoa** [comment]
Cool, i'll wait for your feedback.

**Comment by Marak** [comment]
@vrunoa - When visiting that URL I now get:

```
An error occurred with user-submitted code 
        at IncomingMessage.<anonymous> (/root/hook.io/lib/resources/hook/fetchHookSourceCodeFromGithub.js:70:27)

Error: Not valid JSON: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

**Comment by Marak** [comment]
Not a perfect error message, but should at least not crash now.

**Comment by vrunoa** [comment]
Perfect. Thanks for your feedback
