### ISSUE TITLE
Support JSON payloads

### ISSUE THREAD

**Issue by grncdr** [bigcompany/hook.io#6]
It's pretty common for webhooks to receive a JSON payload, and it would be cool if hook.io supported `application/json` as a content type.

A simpler/smaller change that would immediately improve the experience is adding [collect-stream](https://www.npmjs.org/package/collect-stream) to the module list so I can at least skip the boilerplate for concatenating a stream into a big old string before calling `JSON.parse`.

**Comment by lylepratt** [comment]
JSON payloads seem to be broken right now:
https://github.com/bigcompany/hook.io/issues/40

They all error with:
```
Error communicating with worker 10003

Error: socket hang up
    at createHangUpError (_http_client.js:210:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:898:16
```

**Comment by Marak** [comment]
Good catch! Looks like `jsonParser` is not defined here https://github.com/bigcompany/hook.io/blob/master/lib/resources/hook/parseRequestBody.js#L67

Looks like it was missed during a refactor, patching now.

Having test coverage for this would be nice.

**Comment by Marak** [comment]
Fixed in production. Commit following here shortly.
