### ISSUE TITLE
Spaces in hook name

### ISSUE THREAD

**Issue by DDuarte** [bigcompany/hook.io#78]
When trying to view a hook that has spaces in the name the page gives a 200 OK with the message `Cannot read property 'replace' of undefined`.

Example: http://hook.io/DDuarte/TC%20close%20335%20issue

**Comment by Marak** [comment]
I believe the error might be coming from your hook's source code?

Try this link? http://hook.io/DDuarte/TC%20close%20335%20issue?ref=foo

https://gist.github.com/DDuarte/0581f1378c1ae10128c6#file-close335issues-js-L18

**Comment by Marak** [comment]
Related issue, slugify hook names ( so we don't get URL encoded data ) 

https://github.com/bigcompany/hook.io/issues/74

**Comment by DDuarte** [comment]
Accessing http://hook.io/DDuarte/TC%20close%20335%20issue is executing the hook? That's unexpected (to me, at least)

**Comment by Marak** [comment]
The current behavior is that if you perform GET or POST request to Hook, it will execute.

This is new. Previous behavior was to not explicitly run hook.
