### ISSUE TITLE
No view >=0.7 found during install

### ISSUE THREAD

**Issue by offlinehacker** [bigcompany/hook.io#89]
npm WARN package.json hook.io@1.0.0 No repository field.
npm ERR! notarget No compatible version found: view@'>=0.7.0-0 <0.8.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.5.0","0.6.0","0.6.1"]

**Comment by Marak** [comment]
I just published latest `view` module to npm.

Should be able to install now. If not, just clone `master` from github.

You'll probably need to clone a few other projects at this point. In active development.
