### ISSUE TITLE
Add missing request/response methods.

### ISSUE THREAD

**Issue by ljharb** [bigcompany/hook.io#96]
https://nodejs.org/api/http.html#http_class_http_serverresponse indicates a number of methods not on `hook.res`:
 - hook.res.writeContinue
 - hook.res.writeHead
 - hook.res.setTimeout
 - hook.res.statusCode (getter and setter)
 - hook.res.statusMessage
 - hook.res.setHeader
 - hook.res.headersSent
 - hook.res.sendDate
 - hook.res.getHeader
 - hook.res.removeHeader
 - hook.res.addTrailers

(also, the docs don't link directly to that section, it'd be nice to add the hash marker)

**Comment by Marak** [comment]
Should be easy to add those.

With the new architecture we are accepting events like these as JSON encoding messages over IPC.

There are two places they need to be added. The `run-hook` binary, and the `spawnService.js` file.

https://github.com/bigcompany/hook.io/blob/master/bin/run-hook
https://github.com/bigcompany/hook.io/blob/master/lib/resources/hook/spawnService.js

I'm currently working on both of these files. Will most likely separate the message passing code into a new file.

Will have time to work on this next week. Thanks for the information!

**Comment by ljharb** [comment]
Great, looking forward to it! :-)

**Comment by Marak** [comment]
We've now got a separate file to add these methods: https://github.com/bigcompany/hook.io/blob/master/lib/resources/hook/stderr/responseMethods.js

Feel free to add the method signatures if you have time. It could be mostly done without having to start the app ( just fill in the signatures and I can integrate ).

**Comment by Marak** [comment]
Added back almost all the methods.

Deployed.

The missing methods can be added later.

**Comment by ljharb** [comment]
https://github.com/bigcompany/hook.io/blob/master/lib/resources/hook/stderr/responseMethods.js#L70-L72 doesn't seem to work with `writeHead(301, { Location: url })` - ie, the status works but the header doesn't.

**Comment by ljharb** [comment]
actually it seems like `setHeader` is also not working - https://gist.github.com/ljharb/d3c51ab5042040da0040#file-app-js-L40 isn't getting set properly for me

**Comment by Marak** [comment]
Investigating now.

It's actually working locally so I suspect it's something environment related on the server.

Should be resolved today...

**Comment by Marak** [comment]
@ljharb Appears to be resolved now?

I had forgotten I modified a version of the `run-remote-service` module on production that shouldn't have remained there.

Reset the dependency, but made no code changes.

**Comment by ljharb** [comment]
Awesome, this looks great! Thanks!
