### ISSUE TITLE
Feature request: pretty URLs with parameters

### ISSUE THREAD

**Issue by ljharb** [bigcompany/hook.io#97]
I'd love something like an express url (`'foo/:bar/baz/:quux'`) which would map `'foo/1/baz/2'` to params such that `hook.params.bar === 1 && hook.params.quux === 2`.

I'm not particularly concerned with the syntax - I'm not even sure whether it'd be better in the code, or in the configuration interface on the web (probably the code) - but I'd love to not force users to see query params.

**Comment by Marak** [comment]
This can and should be done. A few others have asked for it.

Probably the best way to do it is to allow the `:` character in the name of service.

From here it should be a matter of setting up a custom middleware to perform the parsing of any additional parameters past `/:owner/:name`

Will be a top priority for next week

**Comment by ljharb** [comment]
Since I can't edit the name of a service (another feature request, perhaps), that means I'd have to delete and recreate my service every time I want to edit the parameters or URL paths?

**Comment by Marak** [comment]
@ljharb - Editing the service url seems pretty important.

Opened up a new issue #98 for that feature.

**Comment by Marak** [comment]
@ljharb - I've got this working locally now. Implementation uses a new string property `Hook.path` which allows for arbitrary url route parameters.

Will continue to test / refactor some of the route handling logic.

Should have something deployed in the next couple of days.

**Comment by ljharb** [comment]
Awesome, thanks!

**Comment by Marak** [comment]
Deployed and working. Will continue to test.
